# -*- coding: utf-8 -*-
"""
conftest.py
-----------
LegacyLift -- shared pytest configuration.

The LEGACYLIFT_SRC environment variable controls which source directory is
loaded by the characterization tests.  Default: modernized/src.

No compatibility shim is needed here: the golden files are generated by
tools/run_capture.sh (Python 2.7 Docker), and the tests themselves run either
against the modernised source (Python 3) or the legacy source inside the
Python 2.7 Docker container via tools/run_legacy_tests.sh.
"""

import os


def pytest_configure(config):
    # Intentionally empty -- path injection is handled in test_characterization.py
    # via the add_src_to_path session fixture, which reads LEGACYLIFT_SRC.
    pass
