# -*- coding: utf-8 -*-
"""
tests/test_characterization.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
LegacyLift -- Protect stage.

Golden-master characterization tests for the three in-scope legacy modules:
  - network      (legacy-target/src/network.py)
  - network2     (legacy-target/src/network2.py)
  - mnist_loader (legacy-target/src/mnist_loader.py)

Golden JSON files in tests/golden/ are produced by running:
    bash tools/run_capture.sh          (Python 2.7 via Docker)

The code-under-test is resolved from the environment variable LEGACYLIFT_SRC.
Default (after modernisation): modernized/src

Run against the legacy source to verify the Python 2.7 baseline:
    bash tools/run_legacy_tests.sh

All numeric comparisons use np.allclose(rtol=1e-7).
"""

import json
import os
import sys
import tempfile

import numpy as np
import pytest

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SRC_DIR = os.environ.get(
    "LEGACYLIFT_SRC",
    os.path.join(os.path.dirname(__file__), "..", "modernized", "src"),
)
SRC_DIR = os.path.abspath(SRC_DIR)

GOLDEN_DIR = os.path.join(os.path.dirname(__file__), "golden")


def load_golden(name):
    """Load a golden JSON file by base name (no extension)."""
    path = os.path.join(GOLDEN_DIR, name + ".json")
    with open(path) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Session-scoped fixture: put SRC_DIR on sys.path once per test session
# ---------------------------------------------------------------------------
@pytest.fixture(scope="session", autouse=True)
def add_src_to_path():
    if SRC_DIR not in sys.path:
        sys.path.insert(0, SRC_DIR)


# ===========================================================================
# ### BEGIN network section ###
# ===========================================================================

class TestNetwork:
    """Characterization tests for the ``network`` module (network.py).

    Each test loads a pre-captured golden JSON snapshot and asserts that
    the module under test produces bit-for-bit (within floating-point
    tolerance) identical outputs.  The golden files are generated by
    ``tools/capture_golden.py`` against the *original* Python 2.7 source.
    """

    # ------------------------------------------------------------------
    # sigmoid
    # ------------------------------------------------------------------

    def test_sigmoid_1d(self):
        """sigmoid applied to a 1-D array matches the golden snapshot."""
        import network

        golden = load_golden("network_sigmoid")
        z = np.array(golden["z_1d"])
        expected = np.array(golden["sigmoid_z_1d"])
        result = network.sigmoid(z)
        assert np.allclose(result, expected, rtol=1e-7)

    def test_sigmoid_2d(self):
        """sigmoid applied to a 2-D array matches the golden snapshot."""
        import network

        golden = load_golden("network_sigmoid")
        z = np.array(golden["z_2d"])
        expected = np.array(golden["sigmoid_z_2d"])
        result = network.sigmoid(z)
        assert np.allclose(result, expected, rtol=1e-7)

    # ------------------------------------------------------------------
    # sigmoid_prime
    # ------------------------------------------------------------------

    def test_sigmoid_prime_1d(self):
        """sigmoid_prime applied to a 1-D array matches the golden snapshot."""
        import network

        golden = load_golden("network_sigmoid_prime")
        z = np.array(golden["z_1d"])
        expected = np.array(golden["sigmoid_prime_z_1d"])
        result = network.sigmoid_prime(z)
        assert np.allclose(result, expected, rtol=1e-7)

    def test_sigmoid_prime_2d(self):
        """sigmoid_prime applied to a 2-D array matches the golden snapshot."""
        import network

        golden = load_golden("network_sigmoid_prime")
        z = np.array(golden["z_2d"])
        expected = np.array(golden["sigmoid_prime_z_2d"])
        result = network.sigmoid_prime(z)
        assert np.allclose(result, expected, rtol=1e-7)

    # ------------------------------------------------------------------
    # feedforward
    # ------------------------------------------------------------------

    def test_feedforward_output(self):
        """Network.feedforward produces the golden output for fixed weights."""
        import network

        golden = load_golden("network_feedforward")
        net = network.Network(golden["sizes"])
        net.biases = [np.array(b) for b in golden["biases"]]
        net.weights = [np.array(w) for w in golden["weights"]]
        x = np.array(golden["x"])
        expected = np.array(golden["output"])
        result = net.feedforward(x)
        assert np.allclose(result, expected, rtol=1e-7)

    # ------------------------------------------------------------------
    # backprop
    # ------------------------------------------------------------------

    def test_backprop_nabla_b(self):
        """Network.backprop returns nabla_b layers matching the golden snapshot."""
        import network

        golden = load_golden("network_backprop")
        net = network.Network(golden["sizes"])
        net.biases = [np.array(b) for b in golden["biases"]]
        net.weights = [np.array(w) for w in golden["weights"]]
        x = np.array(golden["x"])
        y = np.array(golden["y"])
        nabla_b, _ = net.backprop(x, y)
        expected_nabla_b = [np.array(nb) for nb in golden["nabla_b"]]
        for layer_idx, (result_layer, expected_layer) in enumerate(
            zip(nabla_b, expected_nabla_b)
        ):
            assert np.allclose(result_layer, expected_layer, rtol=1e-7), (
                "nabla_b mismatch at layer {}".format(layer_idx)
            )

    def test_backprop_nabla_w(self):
        """Network.backprop returns nabla_w layers matching the golden snapshot."""
        import network

        golden = load_golden("network_backprop")
        net = network.Network(golden["sizes"])
        net.biases = [np.array(b) for b in golden["biases"]]
        net.weights = [np.array(w) for w in golden["weights"]]
        x = np.array(golden["x"])
        y = np.array(golden["y"])
        _, nabla_w = net.backprop(x, y)
        expected_nabla_w = [np.array(nw) for nw in golden["nabla_w"]]
        for layer_idx, (result_layer, expected_layer) in enumerate(
            zip(nabla_w, expected_nabla_w)
        ):
            assert np.allclose(result_layer, expected_layer, rtol=1e-7), (
                "nabla_w mismatch at layer {}".format(layer_idx)
            )

    # ------------------------------------------------------------------
    # evaluate
    # ------------------------------------------------------------------

    def test_evaluate_score(self):
        """Network.evaluate returns the exact golden integer score."""
        import network

        golden = load_golden("network_evaluate")
        net = network.Network(golden["sizes"])
        net.biases = [np.array(b) for b in golden["biases"]]
        net.weights = [np.array(w) for w in golden["weights"]]
        dataset = [(np.array(entry["x"]), int(entry["y"])) for entry in golden["dataset"]]
        result = net.evaluate(dataset)
        assert result == int(golden["score"])

    # ------------------------------------------------------------------
    # update_mini_batch
    # ------------------------------------------------------------------

    def test_update_mini_batch_float_eta(self):
        """update_mini_batch with eta=3.0 (float) matches the golden state_after."""
        import network

        golden = load_golden("network_update_mini_batch_float_eta")
        net = network.Network(golden["sizes"])
        net.biases = [np.array(b) for b in golden["state_before"]["biases"]]
        net.weights = [np.array(w) for w in golden["state_before"]["weights"]]
        mini_batch = [
            (np.array(sample["x"]), np.array(sample["y"]))
            for sample in golden["mini_batch"]
        ]
        net.update_mini_batch(mini_batch, 3.0)
        expected_biases = [np.array(b) for b in golden["state_after"]["biases"]]
        expected_weights = [np.array(w) for w in golden["state_after"]["weights"]]
        for i, (result_b, expected_b) in enumerate(zip(net.biases, expected_biases)):
            assert np.allclose(result_b, expected_b, rtol=1e-7), (
                "biases mismatch at layer {} after update_mini_batch (float eta)".format(i)
            )
        for i, (result_w, expected_w) in enumerate(zip(net.weights, expected_weights)):
            assert np.allclose(result_w, expected_w, rtol=1e-7), (
                "weights mismatch at layer {} after update_mini_batch (float eta)".format(i)
            )

    @pytest.mark.xfail(
        sys.version_info >= (3,),
        strict=True,
        reason=(
            "Python 2 integer-division: 3/2 == 1 (floor). "
            "Golden captured on Python 2.7 with batch_size=2, eta=3. "
            "Python 3 computes 3/2 == 1.5 (true division), producing different weights. "
            "Marked xfail only on Python 3; passes unconditionally on Python 2.7."
        ),
    )
    def test_update_mini_batch_int_eta(self):
        """Captures Python 2 integer-division: eta=3 (int), batch_size=2.

        With len(mini_batch)=2 and eta=3:
          Python 2.7: 3/2 == 1   (floor division -- weights scaled by 1)
          Python 3:   3/2 == 1.5 (true division  -- weights scaled by 1.5)
        The golden values were produced by Python 2.7 and reflect floor-division.
        This test is expected to FAIL on Python 3 and PASS on Python 2.7.
        After modernisation, fix eta/len(mini_batch) -> eta/float(len(mini_batch)).
        """
        import network

        golden = load_golden("network_update_mini_batch_int_eta")
        net = network.Network(golden["sizes"])
        net.biases = [np.array(b) for b in golden["state_before"]["biases"]]
        net.weights = [np.array(w) for w in golden["state_before"]["weights"]]
        mini_batch = [
            (np.array(sample["x"]), np.array(sample["y"]))
            for sample in golden["mini_batch"]
        ]
        net.update_mini_batch(mini_batch, 3)  # integer eta — Python 2: 3/2=1, Python 3: 3/2=1.5
        expected_biases = [np.array(b) for b in golden["state_after"]["biases"]]
        expected_weights = [np.array(w) for w in golden["state_after"]["weights"]]
        for i, (result_b, expected_b) in enumerate(zip(net.biases, expected_biases)):
            assert np.allclose(result_b, expected_b, rtol=1e-7), (
                "biases mismatch at layer {} after update_mini_batch (int eta)".format(i)
            )
        for i, (result_w, expected_w) in enumerate(zip(net.weights, expected_weights)):
            assert np.allclose(result_w, expected_w, rtol=1e-7), (
                "weights mismatch at layer {} after update_mini_batch (int eta)".format(i)
            )

# ### END network section ###


# ===========================================================================
# ### BEGIN network2 section ###
# ===========================================================================

class TestNetwork2:
    """Characterization tests for the ``network2`` module (network2.py)."""

    # ------------------------------------------------------------------
    # Cost functions
    # ------------------------------------------------------------------

    def test_quadratic_cost_fn(self):
        import network2
        g = load_golden("network2_quadratic_cost")
        a = np.array(g["a"])
        y = np.array(g["y"])
        result = network2.QuadraticCost.fn(a, y)
        assert np.allclose(result, g["fn"], rtol=1e-7)

    def test_quadratic_cost_delta(self):
        import network2
        g = load_golden("network2_quadratic_cost")
        z = np.array(g["z"])
        a = np.array(g["a"])
        y = np.array(g["y"])
        result = network2.QuadraticCost.delta(z, a, y)
        assert np.allclose(result, np.array(g["delta"]), rtol=1e-7)

    def test_crossentropy_cost_fn(self):
        import network2
        g = load_golden("network2_crossentropy_cost")
        a = np.array(g["a"])
        y = np.array(g["y"])
        result = network2.CrossEntropyCost.fn(a, y)
        assert np.allclose(result, g["fn"], rtol=1e-7)

    def test_crossentropy_cost_delta(self):
        import network2
        g = load_golden("network2_crossentropy_cost")
        z = np.array(g["z"])
        a = np.array(g["a"])
        y = np.array(g["y"])
        result = network2.CrossEntropyCost.delta(z, a, y)
        assert np.allclose(result, np.array(g["delta"]), rtol=1e-7)

    # ------------------------------------------------------------------
    # Feedforward / backprop
    # ------------------------------------------------------------------

    def _build_net_from_golden(self, network2, g):
        """Reconstruct a Network2 instance from golden biases/weights."""
        net = network2.Network(g["sizes"])
        net.biases = [np.array(b) for b in g["biases"]]
        net.weights = [np.array(w) for w in g["weights"]]
        return net

    def test_feedforward_output(self):
        import network2
        g = load_golden("network2_feedforward_backprop")
        net = self._build_net_from_golden(network2, g)
        x = np.array(g["x"])
        result = net.feedforward(x)
        assert np.allclose(result, np.array(g["feedforward_output"]), rtol=1e-7)

    def test_backprop_nabla_b(self):
        import network2
        g = load_golden("network2_feedforward_backprop")
        net = self._build_net_from_golden(network2, g)
        x = np.array(g["x"])
        y = np.array(g["y"])
        nabla_b, _ = net.backprop(x, y)
        for layer_idx, (computed, expected) in enumerate(zip(nabla_b, g["nabla_b"])):
            assert np.allclose(computed, np.array(expected), rtol=1e-7), (
                "nabla_b mismatch at layer {}".format(layer_idx)
            )

    def test_backprop_nabla_w(self):
        import network2
        g = load_golden("network2_feedforward_backprop")
        net = self._build_net_from_golden(network2, g)
        x = np.array(g["x"])
        y = np.array(g["y"])
        _, nabla_w = net.backprop(x, y)
        for layer_idx, (computed, expected) in enumerate(zip(nabla_w, g["nabla_w"])):
            assert np.allclose(computed, np.array(expected), rtol=1e-7), (
                "nabla_w mismatch at layer {}".format(layer_idx)
            )

    # ------------------------------------------------------------------
    # update_mini_batch
    # ------------------------------------------------------------------

    def _run_update_mini_batch(self, network2, golden_name, eta):
        g = load_golden(golden_name)
        net = network2.Network(g["sizes"])
        net.biases = [np.array(b) for b in g["state_before"]["biases"]]
        net.weights = [np.array(w) for w in g["state_before"]["weights"]]
        mini_batch = [
            (np.array(sample["x"]), np.array(sample["y"]))
            for sample in g["mini_batch"]
        ]
        net.update_mini_batch(mini_batch, eta, lmbda=g["lmbda"], n=g["n"])
        return net, g

    def test_update_mini_batch_float_eta(self):
        import network2
        net, g = self._run_update_mini_batch(
            network2, "network2_update_mini_batch_float_eta", eta=3.0
        )
        for i, (computed, expected) in enumerate(
            zip(net.biases, g["state_after"]["biases"])
        ):
            assert np.allclose(computed, np.array(expected), rtol=1e-7), (
                "biases mismatch at layer {} (float eta)".format(i)
            )
        for i, (computed, expected) in enumerate(
            zip(net.weights, g["state_after"]["weights"])
        ):
            assert np.allclose(computed, np.array(expected), rtol=1e-7), (
                "weights mismatch at layer {} (float eta)".format(i)
            )

    @pytest.mark.xfail(
        sys.version_info >= (3,),
        strict=True,
        reason=(
            "Python 2 integer-division: 3/2 == 1 (floor). "
            "Golden captured on Python 2.7 with batch_size=2, eta=3. "
            "Python 3 computes 3/2 == 1.5 (true division), producing different weights. "
            "Marked xfail only on Python 3; passes unconditionally on Python 2.7."
        ),
    )
    def test_update_mini_batch_int_eta(self):
        """Captures Python 2 integer-division: eta=3 (int), batch_size=2.

        With len(mini_batch)=2 and eta=3:
          Python 2.7: 3/2 == 1   (floor division -- weights scaled by 1)
          Python 3:   3/2 == 1.5 (true division  -- weights scaled by 1.5)
        Golden values were produced on Python 2.7 and reflect floor-division.
        This test is expected to FAIL on Python 3 and PASS on Python 2.7.
        After modernisation, fix eta/len(mini_batch) -> eta/float(len(mini_batch)).
        """
        import network2
        net, g = self._run_update_mini_batch(
            network2, "network2_update_mini_batch_int_eta", eta=3
        )
        for i, (computed, expected) in enumerate(
            zip(net.biases, g["state_after"]["biases"])
        ):
            assert np.allclose(computed, np.array(expected), rtol=1e-7), (
                "biases mismatch at layer {} (int eta)".format(i)
            )
        for i, (computed, expected) in enumerate(
            zip(net.weights, g["state_after"]["weights"])
        ):
            assert np.allclose(computed, np.array(expected), rtol=1e-7), (
                "weights mismatch at layer {} (int eta)".format(i)
            )

    # ------------------------------------------------------------------
    # save / load round-trip
    # ------------------------------------------------------------------

    def test_save_load_feedforward(self):
        """save() then load() reproduces identical feedforward output."""
        import network2
        g = load_golden("network2_save_load")
        net = network2.Network(g["sizes"])
        # Restore exact weights from the golden so the test is deterministic
        # regardless of random-seed differences between runs.
        net.biases = [np.array(b) for b in g["biases"]]
        net.weights = [np.array(w) for w in g["weights"]]
        x = np.array(g["x"])
        output_before = net.feedforward(x)
        assert np.allclose(output_before, np.array(g["feedforward_before"]), rtol=1e-7), (
            "feedforward before save does not match golden"
        )
        tmp = tempfile.NamedTemporaryFile(suffix=".json", delete=False)
        tmp.close()
        try:
            net.save(tmp.name)
            net_loaded = network2.load(tmp.name)
        finally:
            os.unlink(tmp.name)
        output_after = net_loaded.feedforward(x)
        assert np.allclose(output_after, np.array(g["feedforward_after"]), rtol=1e-7)

    def test_save_load_cost_class(self):
        """save() preserves the cost class name; load() restores it."""
        import network2
        g = load_golden("network2_save_load")
        cost_class_name = g["cost_class"]
        cost_class = getattr(network2, cost_class_name)
        net = network2.Network(g["sizes"], cost=cost_class)
        tmp = tempfile.NamedTemporaryFile(suffix=".json", delete=False)
        tmp.close()
        try:
            net.save(tmp.name)
            net_loaded = network2.load(tmp.name)
        finally:
            os.unlink(tmp.name)
        assert net_loaded.cost.__name__ == cost_class_name

# ### END network2 section ###


# ===========================================================================
# ### BEGIN mnist_loader section ###
# ===========================================================================

class TestMnistLoader:
    """Characterization tests for the ``mnist_loader`` module."""

    def test_vectorized_result_shape(self):
        """vectorized_result(d) always returns shape (10, 1)."""
        import mnist_loader
        for digit in range(10):
            result = mnist_loader.vectorized_result(digit)
            assert result.shape == (10, 1), (
                "vectorized_result({}) shape {} != (10, 1)".format(digit, result.shape)
            )

    def test_vectorized_result_values(self):
        """vectorized_result values match the golden snapshot for each digit."""
        import mnist_loader
        golden = load_golden("mnist_loader_vectorized_result")
        for digit in range(10):
            result = mnist_loader.vectorized_result(digit)
            expected = np.array(golden["digits"][str(digit)])
            assert np.allclose(result, expected, rtol=1e-7), (
                "vectorized_result({}) values differ from golden".format(digit)
            )

    def test_vectorized_result_one_hot(self):
        """vectorized_result is a valid one-hot: exactly 1.0 at digit position, 0.0 elsewhere."""
        import mnist_loader
        for digit in range(10):
            result = mnist_loader.vectorized_result(digit)
            flat = result.flatten()
            assert flat[digit] == 1.0, (
                "vectorized_result({}) missing 1.0 at position {}".format(digit, digit)
            )
            for i, val in enumerate(flat):
                if i != digit:
                    assert val == 0.0, (
                        "vectorized_result({}) has non-zero at position {}: {}".format(
                            digit, i, val
                        )
                    )

    def test_load_data_wrapper_lengths(self):
        """Risky behavior: Python 2 zip() returns a list; Python 3 returns an
        iterator. len() on an iterator raises TypeError. Ensures the modernised
        code wraps zip() in list()."""
        import mnist_loader
        golden = load_golden("mnist_loader_load_data_wrapper")
        training_data, validation_data, test_data = mnist_loader.load_data_wrapper()
        assert len(training_data) == golden["training_len"], (
            "training_data length {} != {}".format(len(training_data), golden["training_len"])
        )
        assert len(validation_data) == golden["validation_len"], (
            "validation_data length {} != {}".format(
                len(validation_data), golden["validation_len"]
            )
        )
        assert len(test_data) == golden["test_len"], (
            "test_data length {} != {}".format(len(test_data), golden["test_len"])
        )

    def test_load_data_wrapper_training_shapes(self):
        """First training element has x shape (784,1) and y shape (10,1)."""
        import mnist_loader
        training_data, _va, _te = mnist_loader.load_data_wrapper()
        x, y = training_data[0]
        assert x.shape == (784, 1), "training x[0] shape {} != (784, 1)".format(x.shape)
        assert y.shape == (10, 1), "training y[0] shape {} != (10, 1)".format(y.shape)

    def test_load_data_wrapper_validation_shapes(self):
        """First validation element has x shape (784,1)."""
        import mnist_loader
        _tr, validation_data, _te = mnist_loader.load_data_wrapper()
        x, _y = validation_data[0]
        assert x.shape == (784, 1), "validation x[0] shape {} != (784, 1)".format(x.shape)

    def test_load_data_wrapper_test_shapes(self):
        """First test element has x shape (784,1)."""
        import mnist_loader
        _tr, _va, test_data = mnist_loader.load_data_wrapper()
        x, _y = test_data[0]
        assert x.shape == (784, 1), "test x[0] shape {} != (784, 1)".format(x.shape)

    def test_load_data_wrapper_training_x0_first5(self):
        """First 5 pixel values of training sample 0 match the golden snapshot."""
        import mnist_loader
        golden = load_golden("mnist_loader_load_data_wrapper")
        training_data, _va, _te = mnist_loader.load_data_wrapper()
        x, _y = training_data[0]
        first5 = x.flatten()[:5].tolist()
        assert np.allclose(first5, golden["training_x0_first5"], rtol=1e-7), (
            "training x[0] first 5 values {} differ from golden {}".format(
                first5, golden["training_x0_first5"]
            )
        )

    def test_load_data_wrapper_training_y0_first5(self):
        """First 5 values of training one-hot label 0 match the golden snapshot."""
        import mnist_loader
        golden = load_golden("mnist_loader_load_data_wrapper")
        training_data, _va, _te = mnist_loader.load_data_wrapper()
        _x, y = training_data[0]
        first5 = y.flatten()[:5].tolist()
        assert np.allclose(first5, golden["training_y0_first5"], rtol=1e-7), (
            "training y[0] first 5 values {} differ from golden {}".format(
                first5, golden["training_y0_first5"]
            )
        )

    def test_load_data_wrapper_second_iteration(self):
        """Risky behavior: A bare Python 3 iterator is exhausted after one pass.
        Re-indexing must return the same element. Fails if the modernised code
        returns a generator instead of a list."""
        import mnist_loader
        training_data, _va, _te = mnist_loader.load_data_wrapper()
        x_first, _y = training_data[0]
        x_second, _y2 = training_data[0]
        assert np.allclose(x_first, x_second, rtol=1e-7), (
            "training_data[0] returned different x values on two accesses — "
            "data source may be a generator that was exhausted"
        )

# ### END mnist_loader section ###
